# Getting Started with TensorFlow 2.0 in 7 Days
## 1.3 Getting Started

### Install TensorFlow

In [1]:
# install tensorflow
!pip install tensorflow==2.0.0-alpha0 

    100% |████████████████████████████████| 78.8MB 359kB/s 
    100% |████████████████████████████████| 3.2MB 11.5MB/s 
    100% |████████████████████████████████| 61kB 24.9MB/s 
    100% |████████████████████████████████| 358kB 22.3MB/s 


### Import TensorFlow

In [0]:
import tensorflow as tf

Numeric Python lets us carry out numerical operations in Python, such as declaring matrices. We will import numpy and declare a matrix.

### Import Numpy

In [8]:
import numpy as np

numpy_array = np.ones([5, 5]) #declare 5 rows and 5 columns of 1s
print(numpy_array)
print(numpy_array.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)


We can create a numpy array from a python list. We will create a row vector

In [10]:
numpy_vector = np.asarray([[3.,5.,3.,2.,2.]])
print(numpy_vector)
print(numpy_vector.shape)

[[3. 5. 3. 2. 2.]]
(1, 5)


### Matrix Multiplication
We can use both numpy arrays in a TensorFlow operation that will produce a tensor

In [12]:
tensor = tf.matmul(numpy_array, numpy_vector.T)
print(tensor)

tf.Tensor(
[[15.]
 [15.]
 [15.]
 [15.]
 [15.]], shape=(5, 1), dtype=float64)


There are a few important details to note in the operation above:

*   The 5x5 matrix was generated as an array of floating point numbers, so the matrix that multiples it must use floating point numbers to avoid any errors
*   When creating numpy_vector, we put a . after a number to make it a float
*   When multiplying matrices, the number of rows in the first matrix must equal the number of columns in the second matrix.
*   We apply a transpose to our second matrix to get it into the desired shape for our multiplication. Without it, we would get an error



### Addition
Addition requires both tensors/matrices to be of the same shape. Notice how we add a tensor and a numpy array without any explicit conversions.

In [13]:
tensor_2 = tf.add(tensor, numpy_vector.T)
print(tensor_2)

tf.Tensor(
[[18.]
 [20.]
 [18.]
 [17.]
 [17.]], shape=(5, 1), dtype=float64)


### Broadcasting
Broadcasting lets us use a single value in place of a vector. This will be converted into a vector of the appropriate size on the fly.

In [14]:
tensor_3 = tf.multiply(tensor_2, 3)
print(tensor_3)

tf.Tensor(
[[54.]
 [60.]
 [54.]
 [51.]
 [51.]], shape=(5, 1), dtype=float64)


### Tensors to Numpy Arrays
When you are done working with tensors, you can convert them to numpy arrays either explicitly or implicitly

In [15]:
print(tensor_3.numpy())

[[54.]
 [60.]
 [54.]
 [51.]
 [51.]]


In [16]:
print(np.add(tensor_3, 9))

[[63.]
 [69.]
 [63.]
 [60.]
 [60.]]
