# Getting Started with TensorFlow 2.0 in 7 Days
## 1.5 Understanding Tensors and Dimensionality

In [1]:
# install tensorflow
!pip install tensorflow==2.0.0-alpha0 

    100% |████████████████████████████████| 79.1MB 290kB/s 
    100% |████████████████████████████████| 3.2MB 10.1MB/s 
    100% |████████████████████████████████| 61kB 23.2MB/s 
    100% |████████████████████████████████| 358kB 16.4MB/s 


In [0]:
import tensorflow as tf
from tensorflow import keras
import IPython.display as display
import numpy as np

### 1D Tensor

In [13]:
_a = np.ones(5)
_a = tf.multiply(_a, 1)
print(_a)
print(_a.shape)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)
(5,)


### 2D Tensor

In [14]:
_b = np.ones([2, 5])
_b = tf.multiply(_b, 1)
print(_b)
print(_b.shape)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float64)
(2, 5)


### 3D Tensor

In [4]:
file_path = keras.utils.get_file('cat.jpg', 'https://www.petmd.com/sites/default/files/what-does-it-mean-when-cat-wags-tail.jpg')

49152/47966==============================] - 0s 0us/step


In [5]:
img_raw = tf.io.read_file(file_path)
print(repr(img_raw)[:100]+"...")

<tf.Tensor: id=1, shape=(), dtype=string, numpy=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x...


In [6]:
img_tensor = tf.image.decode_image(img_raw)

print(img_tensor.shape)
print(img_tensor.dtype)

(428, 590, 3)
<dtype: 'uint8'>


In [7]:
img_final = tf.image.resize(img_tensor, [192, 192])
img_final = img_final/255.0
print(img_final.shape)
print(img_final.numpy().min())
print(img_final.numpy().max())

(192, 192, 3)
0.0
1.0


### Slicing

In [15]:
print(_b[:, :3])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float64)


### Reshape

In [17]:
print(tf.reshape(_b, [-1]))

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float64)


In [18]:
print(tf.reshape(_b, [2, 5, 1]))

tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]], shape=(2, 5, 1), dtype=float64)


In [19]:
print(tf.reshape(_b, [2, 5, 1]).shape)

(2, 5, 1)
